// Gina · CRM Strategy — static build
// © 2026 Isaac Antunes. All rights reserved.
//
// Renders one HTML page per language from src/content/*.mjs.
// Usage: node build.mjs  →  index.html (EN) and pt/index.html (PT)

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import en from './src/content/en.mjs';
import pt from './src/content/pt.mjs';
import { esc, pad, each, channelMocks, phoneScreens, winbackFlow, PHONE_CAPTIONS } from './src/markup.mjs';
import { AUTHOR, EMAIL, LINKEDIN, SITE_URL, MAIL_SUBJECT, LANGS, UI } from './src/site.mjs';

const ROOT = dirname(fileURLToPath(import.meta.url));
const COPY = { en, pt };

// Lifecycle bar colours, light → dark, one per stage.
const STAGE_COLORS = ['#e9efe2', '#d9e7cc', '#c3dcae', '#a8d08a', '#7fc453', '#3f9a3a', '#1e6b2e', '#061f16'];
// Horizontal position (%) of each channel stop on the journey track.
const STOPS = [10, 30, 50, 70, 90];


function page(lang) {
  const t = COPY[lang];
  const ui = UI[lang];
  const { html: htmlLang, root } = LANGS[lang];
  const a = (path) => root + path;
  const mailto = `mailto:${EMAIL}?subject=${encodeURIComponent(MAIL_SUBJECT[lang])}`;
  const ogImage = SITE_URL ? `${SITE_URL.replace(/\/$/, '')}/assets/gina-flat.png` : a('assets/gina-flat.png');
  const mocks = channelMocks(t.mk);
  const phones = phoneScreens(t.mob, a);
  const caption = (i) => {
    const [k, title, d] = PHONE_CAPTIONS[i];
    return `<p class="label phone-card__k">${esc(t.mob[k])}</p><h3 class="phone-card__t">${esc(t.mob[title])}</h3><p class="phone-card__d">${esc(t.mob[d])}</p>`;
  };

  const hrefFor = (l) => root + l.path.replace('index.html', '') || './';
  const langSwitch = Object.entries(LANGS).map(([code, l]) =>
    `<a href="${hrefFor(l)}" hreflang="${l.html}"${code === lang ? ' aria-current="page"' : ''}>${l.label}</a>`
  ).join('');

  return `<!DOCTYPE html>
<!--
  Gina · CRM Strategy
  © 2026 ${AUTHOR}. All rights reserved.
  Generated by build.mjs — edit src/ and rebuild instead of editing this file.
-->
<html lang="${htmlLang}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(ui.title)}</title>
  <meta name="description" content="${esc(ui.ogDesc)}">
  <meta name="author" content="${AUTHOR}">
  <meta name="copyright" content="© 2026 ${AUTHOR}">
  <meta name="theme-color" content="#061f16">
  <meta property="og:type" content="website">
  <meta property="og:title" content="${esc(ui.ogTitle)}">
  <meta property="og:description" content="${esc(ui.ogDesc)}">
  <meta property="og:image" content="${ogImage}">
  <meta property="og:locale" content="${htmlLang.replace('-', '_')}">
  ${Object.values(LANGS).map((l) => `<link rel="alternate" hreflang="${l.html}" href="${hrefFor(l)}">`).join('\n  ')}
  <link rel="icon" href="${a('assets/gina-flat.png')}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,200..700;1,9..144,200..700&family=JetBrains+Mono:wght@400;700&display=swap">
  <link rel="stylesheet" href="${a('css/styles.css')}">
  <script src="${a('js/keyed-video.js')}" defer></script>
  <script src="${a('js/journey.js')}" defer></script>
</head>
<body>
<a class="skip" href="#main">${ui.skip}</a>

<nav class="lang" aria-label="${ui.langNav}">${langSwitch}</nav>

<header class="hero section--dark" id="top">
  <div class="wrap">
    <div class="hero__meta"><span>${esc(t.kicker)}</span><span>${esc(t.tools)}</span></div>
    <div class="hero__grid">
      <div>
        <p class="hero__fun">${esc(t.fun)}</p>
        <h1 class="hero__title">${esc(t.h1a)} <span class="em em--signal">${esc(t.h1i)}</span> ${esc(t.h1b)}</h1>
        <div class="hero__lead">${each(t.lead.split('\n\n'), (p) => `<p>${esc(p)}</p>`)}</div>
        <div class="hero__ctas">
          <a class="btn btn--primary" href="${mailto}">${esc(t.cta)}</a>
          <a class="btn btn--ghost" href="#method">${esc(t.cta2)}</a>
        </div>
        <div class="who">
          <p class="eyebrow">${esc(t.whoK)}</p>
          <p>${esc(t.whoA)} <span class="em">${AUTHOR}</span>${esc(t.whoV)}</p>
          <a class="who__link" href="${LINKEDIN}" target="_blank" rel="noopener"><span class="who__in" aria-hidden="true">in</span>${esc(t.whoL)} ↗</a>
        </div>
      </div>
      <div class="hero__art">
        <keyed-video src="${a('assets/gina-anim-wave.mp4')}" crop="290,30,700,600" masks="842,0,200,180|280,576,225,144|945,0,60,720" poster="${a('assets/gina-flat.png')}" aria-hidden="true"></keyed-video>
      </div>
    </div>
  </div>
</header>

<main id="main">

<section class="section wrap" aria-labelledby="s1">
  <p class="eyebrow">${esc(t.s1)}</p>
  <h2 class="title title--narrow" id="s1">${esc(t.h2a)} <span class="strike">${esc(t.h2s)}</span> <span class="em em--accent">${esc(t.h2i)}</span></h2>
  <div class="grid hairline breaks">${each(t.breaks, (b) => `
    <article class="break">
      <span class="break__k">${b.k}</span>
      <h3 class="break__t">${esc(b.a)} <span class="em">${esc(b.i)}</span></h3>
      <p class="break__d">${esc(b.d)}</p>
    </article>`)}
  </div>
</section>

<section class="section section--dark" id="method" aria-labelledby="s2">
  <div class="wrap">
    <p class="eyebrow">${esc(t.s2)}</p>
    <h2 class="title title--method" id="s2">${esc(t.h3a)} <span class="em">${esc(t.h3b)}</span> <span class="tag-mono">${esc(t.h3c)}</span></h2>
    <ol class="steps">${each(t.steps, (s) => `
      <li class="grid step">
        <div class="step__head"><span class="step__n">${s.n}</span><h3 class="step__name">${esc(s.name)}</h3></div>
        <p class="step__what">${esc(s.what)}</p>
        <div class="step__col"><p class="step__label">${esc(t.inAny)}</p><p class="step__tool">${esc(s.tool)}</p></div>
        <div class="step__col"><p class="step__label">${esc(t.deliv)}</p><p class="step__out">${esc(s.out)}</p><span class="chip">@${esc(s.agent)}</span></div>
      </li>`)}
    </ol>
  </div>
</section>

<section class="section wrap" aria-labelledby="s3">
  <p class="eyebrow">${esc(t.s3)}</p>
  <h2 class="title" id="s3">${esc(t.h4a)} <span class="em em--underline">${esc(t.h4i)}</span> ${esc(t.h4b)}</h2>
  <ol class="grid stages">${each(t.stages, (st, i) => `
    <li class="stage" style="--c:${STAGE_COLORS[i]}">
      <span class="stage__bar"></span>
      <span class="stage__n">${pad(i)}</span>
      <h3 class="stage__name">${esc(st.name)}</h3>
      <p class="stage__rule">${esc(st.rule)}</p>
    </li>`)}
  </ol>
  <div class="grid rules">${each(t.rules, (r) => `
    <p class="rule"><span class="label">${esc(r.k)} · </span>${esc(r.v)}</p>`)}
  </div>
</section>

<section class="section" aria-labelledby="sJ" data-journey>
  <div class="wrap">
    <p class="eyebrow">${esc(t.sJ)}</p>
    <h2 class="title" id="sJ">${esc(t.hJa)} <span class="em em--underline">${esc(t.hJi)}</span></h2>
    <p class="intro">${esc(t.pJ)}</p>

    <div class="track" aria-hidden="true">
      <div class="track__line"></div>
      ${each(STOPS, (x) => `<span class="track__stop" style="--x:${x}%" data-stop></span>`)}
      <img class="walker" src="${a('assets/gina-walk/f1.png')}" alt="" data-walker data-frames="${a('assets/gina-walk/')}">
    </div>

    <div class="grid channels">${each(t.chans, (c, i) => `
      <article class="channel" data-channel>
        <span class="label channel__k">${pad(i)} · ${esc(c.name)}</span>
        ${mocks[i]}
        <p class="channel__learn">${esc(c.learn)}</p>
        <p class="channel__why">${esc(c.why)}</p>
      </article>`)}
    </div>

    <div class="profile">
      <p class="eyebrow">${esc(t.profK)}</p>
      <ul class="profile__traits">${each(t.chans, (c) => `<li data-trait>${esc(c.trait)}</li>`)}</ul>
    </div>
  </div>
</section>

<section class="section section--mint" aria-labelledby="s4">
  <div class="wrap">
    <p class="eyebrow">${esc(t.s4)}</p>
    <h2 class="title" id="s4">${esc(t.h5a)} <span class="em">${esc(t.h5i)}</span></h2>
    ${winbackFlow(t.wf, a)}
  </div>
</section>

<section class="section section--dark" aria-labelledby="sM">
  <div class="wrap">
    <p class="eyebrow">${esc(t.sM)}</p>
    <div class="split">
      <h2 class="title" id="sM">${esc(t.hMa)} <span class="em em--signal">${esc(t.hMi)}</span> ${esc(t.hMb)}</h2>
      <p class="mobile__lead">${esc(t.mLead)}</p>
    </div>

    <div class="grid phones">${each(phones, (phone, i) => `
      <figure class="phone-card">
        ${phone}
        <figcaption>${caption(i)}</figcaption>
      </figure>`)}
    </div>

    <div class="grid mobile__details">
      <div>
        <h3 class="label list-head">${esc(t.mob.prinH)}</h3>
        <dl>${each(t.mob.prin, (p) => `
          <div class="list-row list-row--pair"><dt class="list-row__k">${esc(p.k)}</dt><dd class="list-row__v">${esc(p.v)}</dd></div>`)}
        </dl>
      </div>
      <div class="mobile__stack">
        <div>
          <h3 class="label list-head">${esc(t.mob.chH)}</h3>
          <dl>${each(t.mob.ch, (c) => `
            <div class="list-row list-row--channel"><dt class="list-row__k">${esc(c.k)}</dt><dd class="list-row__v">${esc(c.v)}</dd></div>`)}
          </dl>
        </div>
        <div>
          <h3 class="label list-head">${esc(t.mob.kpiH)}</h3>
          <dl>${each(t.mob.kpi, (k) => `
            <div class="list-row list-row--kpi"><dt class="list-row__k">${esc(k.n)}</dt><dd class="list-row__f">${esc(k.f)}</dd></div>`)}
          </dl>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section wrap" aria-labelledby="s5">
  <p class="eyebrow">${esc(t.s5)}</p>
  <h2 class="title" id="s5">${esc(t.h6a)} <span class="em em--accent">${esc(t.h6i)}</span></h2>
  <ol class="grid levels">${each(t.lv, (l, i) => `
    <li class="level"><span class="level__n">L${i + 1}</span><h3 class="level__name">${esc(l.n)}</h3><p class="level__d">${esc(l.d)}</p></li>`)}
  </ol>
</section>

<section class="section section--dark" aria-labelledby="s6">
  <div class="wrap">
    <p class="eyebrow">${esc(t.s6)}</p>
    <h2 class="title" id="s6"><span class="num">${esc(t.h7n)}</span> ${esc(t.h7a)} <span class="em">${esc(t.h7i)}</span></h2>
    <div class="grid hairline metrics">${each(t.metrics, (m) => `
      <article class="metric"><h3 class="metric__name">${esc(m.name)}</h3><p class="metric__f">${esc(m.f)}</p><p class="metric__why">${esc(m.why)}</p></article>`)}
    </div>
  </div>
</section>

<section class="section wrap" aria-labelledby="s7">
  <p class="eyebrow">${esc(t.s7)}</p>
  <h2 class="title" id="s7">${esc(t.h8a)} <span class="em em--accent">${esc(t.h8i)}</span></h2>
  <ol class="grid phases">${each(t.phases, (p) => `
    <li class="phase"><p class="phase__d">${esc(p.d)}</p><h3 class="phase__n">${esc(p.n)}</h3><p class="phase__o">${esc(p.o)}</p></li>`)}
  </ol>
</section>

<section class="section section--sand" aria-labelledby="s8">
  <div class="wrap">
    <p class="eyebrow">${esc(t.s8)}</p>
    <h2 class="title" id="s8">${esc(t.h9a)} <span class="em em--accent">${esc(t.h9i)}</span></h2>
    <p class="intro">${esc(t.critLead)}</p>
    <div class="grid hairline crit">${each(t.crit, (c) => `
      <article class="crit__item">
        <h3 class="crit__p"><span class="crit__n">${c.n}</span>${esc(c.p)}</h3>
        <p class="crit__why">${esc(c.why)}</p>
        <p class="crit__fix"><span class="label">${esc(t.fix)} → </span><span class="em">${esc(c.fix)}</span></p>
      </article>`)}
    </div>
  </div>
</section>

<section class="section section--dark" aria-labelledby="s9">
  <div class="wrap">
    <p class="eyebrow">${esc(t.s9)}</p>
    <div class="split split--zero">
      <h2 class="zero__title" id="s9">Gina <span class="em em--signal">Zero.</span> <span class="zero__price">R$0</span></h2>
      <p class="mobile__lead">${esc(t.zeroLead)}</p>
    </div>
    <div class="grid stack">${each(t.stack, (z) => `
      <article class="stack__item"><p class="label stack__k">${esc(z.k)}</p><h3 class="stack__v">${esc(z.v)}</h3><p class="stack__d">${esc(z.d)}</p></article>`)}
    </div>
    <div class="grid zero__details">
      <div>
        <h3 class="label list-head">${esc(t.zeroWeeks)}</h3>
        <dl>${each(t.weeks, (w) => `
          <div class="list-row list-row--week"><dt class="list-row__k">${esc(w.w)}</dt><dd class="list-row__v">${esc(w.t)}</dd></div>`)}
        </dl>
      </div>
      <div>
        <h3 class="label list-head">${esc(t.zeroLimits)}</h3>
        <ul>${each(t.limits, (l) => `
          <li class="list-row list-row--limit">${esc(l)}</li>`)}
        </ul>
        <p class="prompt">${esc(t.prompt)}</p>
      </div>
    </div>
  </div>
</section>

<section class="section section--signal close" aria-labelledby="close">
  <div class="wrap grid close__grid">
    <div>
      <h2 class="close__title" id="close">${esc(t.closeA)} <span class="em">${esc(t.closeI)}</span></h2>
      <p class="close__p">${esc(t.closeP)}</p>
      <a class="btn btn--dark" href="${mailto}">${esc(t.cta)}</a>
      <p class="close__tools">HubSpot · RD Station · Pipedrive · Kommo · Zoho · Google Sheets</p>
    </div>
    <img class="close__art" src="${a('assets/gina-flat.png')}" alt="Gina" width="460" height="539" loading="lazy">
  </div>
</section>

</main>

<footer class="footer">
  <div class="wrap">
    <div class="footer__legal">
      <p><strong>${esc(ui.rights)}</strong></p>
      <p>${esc(ui.rightsDetail)}</p>
      <p>${esc(ui.fiction)}</p>
    </div>
    <nav class="footer__links" aria-label="${AUTHOR}">
      <a href="${mailto}">${EMAIL}</a>
      <a href="${LINKEDIN}" target="_blank" rel="noopener">LinkedIn ↗</a>
      <a href="#top">${ui.top}</a>
    </nav>
  </div>
</footer>

</body>
</html>
`;
}

for (const lang of Object.keys(LANGS)) {
  const out = join(ROOT, LANGS[lang].path);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, page(lang));
  console.log('built', LANGS[lang].path);
}
